### ISSUE TITLE
:Neoformat isn't saving cursor position

### ISSUE THREAD

**Issue by adamyonk** [sbdchd/neoformat#55] opened 2017-02-17 18:31 UTC
Tried with both prettier and js-beautify. Here's a gif example:

![feb-17-2017 10-49-59](https://cloud.githubusercontent.com/assets/33258/23078074/d174a890-f50c-11e6-9dfe-06ad2256093e.gif)

**Comment by sbdchd** [comment] 2017-02-17 19:45
Did a git bisect and it seems the issue resides with the following commit:
4c454b3ad30b06fb4978150320ff068fecff4f45

I think the issue is with how `Neoformat` retrieves the buffer data: https://github.com/sbdchd/neoformat/blob/master/autoload/neoformat.vim#L98-L99

**Comment by sbdchd** [comment] 2017-02-17 20:09
If I don't add

```
let g:neoformat_enabled_javascript = ['prettier']
let g:neoformat_enabled_jsx = ['prettier']
autocmd! BufWritePre *.js Neoformat
```

To my config, and instead call Neoformat from vim by hand, the issue doesn't occur. Weird.

**Comment by adamyonk** [comment] 2017-02-17 20:29
Interesting, that still happens for me:

![feb-17-2017 14-28-36](https://cloud.githubusercontent.com/assets/33258/23082103/7bc2b85e-f51d-11e6-9f89-0a27d9d14432.gif)

**Comment by sbdchd** [comment] 2017-03-04 21:05
Can you see if the following diff fixes the bug?

```diff
diff --git a/autoload/neoformat.vim b/autoload/neoformat.vim
index 7157f97..d8ff823 100644
--- a/autoload/neoformat.vim
+++ b/autoload/neoformat.vim
@@ -71,8 +71,8 @@ function! s:neoformat(bang, user_input, start_line, end_line) abort
             continue
         endif
 
-        let stdin = getbufline(bufnr('%'), a:start_line, a:end_line)
-        let original_buffer = getbufline(bufnr('%'), 1, '$')
+        let stdin = getline(a:start_line, a:end_line)
+        let original_buffer = getline(1, '$')
 
         call neoformat#utils#log(stdin)
 
@@ -95,8 +95,8 @@ function! s:neoformat(bang, user_input, start_line, end_line) abort
         call neoformat#utils#log(stdout)
         if !v:shell_error
             " 1. append the lines that are before and after the formatterd content
-            let lines_after = getbufline(bufnr('%'), a:end_line + 1, '$')
-            let lines_before = getbufline(bufnr('%'), 1, a:start_line - 1)
+            let lines_after = getline(a:end_line + 1, '$')
+            let lines_before = getline(1, a:start_line - 1)
 
             let new_buffer = lines_before + stdout + lines_after
             if new_buffer != original_buffer
```

**Comment by adamyonk** [comment] 2017-03-06 16:55
Here's what I'm seeing with that patch: 
![mar-06-2017 10-53-48](https://cloud.githubusercontent.com/assets/33258/23620064/4b47915e-025b-11e7-93ae-510dade680e1.gif)

In the first file, it keeps snapping back to line 3 for some crazy reason, and in the second file I go open, it still snaps back to line 1.

**Comment by sourcesoft** [comment] 2017-03-24 11:33
happens to me too even if I call :Neoformat manually inside neovim.

But I just realized it  happens only if I have `import styled from 'styled-components';`
Somehow `styled-components` has a conflict with the neoformat not sure why. It works just fine if I don't have any other imports other that `styled-components`

Any idea?

**Comment by sourcesoft** [comment] 2017-03-24 11:34
@adamyonk I see you're using `styled-components` too in your gifs 😄

**Comment by tonico** [comment] 2017-03-24 11:45
@sourcesoft Thanks for the hint! I removed `Plug 'fleischie/vim-styled-components'` and now I don't have this issue any more.

**Comment by sourcesoft** [comment] 2017-03-24 13:11
@tonico but that was a handy plugin I need.

**Comment by fleischie** [comment] 2017-03-27 09:47
Hey All,

I think I found the origin of the cursor-jump. It's due to a `search()` statement in the syntax-file (for everyone interested: [fleischie/vim-styled-components/after/syntax/javascript.vim#L56,L57](https://github.com/fleischie/vim-styled-components/blob/19ceed25bcfeb45751d33e71c8beff33d2f238b6/after/syntax/javascript.vim#L56,L57)

I'll consult the vim docs and keep you updated on the progress. Sorry for the inconvenience.

**Comment by fleischie** [comment] 2017-03-27 09:49
Update: I just have to pass the 'n' flag to the `search`-call. :man_facepalming: Will upload fix shortly.

**Comment by sbdchd** [comment] 2017-03-28 02:24
@fleischie Thanks! I am closing this issue for now.

If someone has the issue again, feel free to reopen or create a new issue.

**Closed by sbdchd** 2017-03-28 02:24 UTC
Labels: bug
